# Generated by Django 5.2.8 on 2025-11-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=100)),
                ('bookCover', models.ImageField(upload_to='images')),
                ('bookAuthor', models.CharField(max_length=50)),
                ('bookReview', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
