# Generated by Django 5.2.8 on 2025-11-24 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomspersonal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
    ]
