# Generated by Django 5.2.8 on 2025-11-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomspersonal', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookCover',
            field=models.CharField(max_length=200),
        ),
    ]
