# Generated by Django 5.2.8 on 2025-11-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomspersonal', '0003_alter_book_bookcover'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photoName', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=200)),
                ('photoLocation', models.CharField(max_length=50)),
                ('photoReview', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
