# Generated by Django 5.2.8 on 2025-11-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomsprofessional', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='careerHighlights',
            new_name='careerHighlight',
        ),
    ]
